export const categories = {
smartphones: "",
laptops: "",
fragrances: "",
skincare: "",
groceries: "",
["home-decoration"]: "",
furniture: "",
tops: "",
wo: "",
smartphones: "",
smartphones: "",
smartphones: "",
smartphones: "",
smartphones: "",
smartphones: "",
smartphones: "",
smartphones: "",
smartphones: "",
smartphones: "",
smartphones: "",
};