import { yekan } from '@/utils/fonts';

//Style
import '@/app/globals.scss';
import "animate.css";

//Component
import Layout from '@/layout/Layout';

//Metadata
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={yekan.className}>

        <Layout>
          {children}
        </Layout>

      </body>
    </html>
  )
}
